umijs/qiankun

- .gitignore
执行 `npm start ` 时 git 检测出大量文件变更
> ignore .cache

- package.json
https://github.com/umijs/qiankun/issues/33
> fix: npm scripts 'build' support cross platform

- package.json
- src/hijackers/timer.ts
- src/index.ts
close https://github.com/umijs/qiankun/issues/47
> :label: fix the error with latest version of @type/nodes

- src/hijackers/timer.ts
- remove ts-ignore at window.setTimeout (https://github.com/umijs/qiankun/pull/48)
> :rotating_light: remove ts-ignore at window.setTimeout

- .fatherrc.js
- examples/main/index.js
- package.json
- tsconfig.cjs.json
- tsconfig.json
close https://github.com/umijs/qiankun/pull/50
> :building_construction: use father-build as build system

- src/sandbox.ts
> :sparkles: restore all the context while app remounted

- src/index.ts
lifecycle array should execute as a promise chain
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/77)
> :bug: made the lifecycle execution to be ordered

- README.md
- src/index.ts
- src/interfaces.ts
- add singular mode and enable it by default
- close https://github.com/umijs/qiankun/issues/78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/79)
> :sparkles: add singular mode and enable it by default

- src/index.ts
- src/interfaces.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/84)
> :sparkles: singular mode could be a validate function

- src/index.ts
- WIP: https://github.com/umijs/qiankun/issues/88 https://github.com/umijs/umi-plugin-qiankun/pull/24
> :package: export LifeCycles type

- src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/95)
> :children_crossing: add global variable to help to identify qiankun context in sub apps

- src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/94)
> :pencil2: defer -> deferred

- README.md
- examples/main/index.js
- examples/main/package.json
- package.json
- src/index.ts
- src/interfaces.ts
- src/prefetch.ts
- support [import-html-entry](https://github.com/kuitos/import-html-entry) custom fetch
- format js, ts, md by [hooks](https://github.com/umijs/qiankun/blob/dab1b086f97528994f29ea9813f81f94159c1a20/package.json#L61)
> :sparkles: support custom fetch

- src/hijackers/dynamicStylesheet.ts
- src/hijackers/index.ts
close https://github.com/umijs/qiankun/pull/51
close https://github.com/umijs/qiankun/issues/38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/111)
> :bug: hijack dynamic stylesheet injection

- src/index.ts
registerMicroApps would trigger the load function of sub app
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/112)
> :bug: move qiankun env variable to the first api invocation

- src/hijackers/dynamicStylesheet.ts
cover the scenario of style tag injection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/114)
> :bug: hijack dynamic style tag injection

- src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/124)
> :label: exports all qiankun types

- .eslintrc.js
- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/125)
> :wrench: update eslint and travis config

- examples/main/Framework.jsx
- src/index.ts
close https://github.com/umijs/qiankun/issues/122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/126)
> :bug: remove app dom after unmount

- .fatherrc.js
- package.json
- src/prefetch.ts
- typings/index.d.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/134)
> :wrench: change transpile mode from rollup to babel

- src/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/135)
> :bug: correct the window fallback logic

- src/hijackers/dynamicStylesheet.ts
- src/hijackers/index.ts
- src/sandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/139)
> :bug: only record the stylesheet injection of special app

- src/index.ts
- src/interfaces.ts
- src/prefetch.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/140)
> :sparkles: support prefetch all for hybrid apps architecture

- src/hijackers/dynamicStylesheet.ts
resolve https://github.com/umijs/qiankun/issues/142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/144)
> :bug: check the node is descendant of head before removing

- .eslintrc.js
- package.json
- src/hijackers/index.ts
- src/hijackers/publicPath.ts
- src/index.ts
- src/interfaces.ts
- src/sandbox.ts
resolve #137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/147)
> :sparkles: inject the asset publicPath before app bootstrap

- src/sandbox.ts
- close https://github.com/umijs/qiankun/issues/90
e.g: 
```js
window.abc = 1;  // emit addedPropsMapInSandbox
// and then
window.abc = 2;  // emit modifiedPropsOriginalValueMapInSandbox
// restore expect modifiedPropsOriginalValueMapInSandbox -->  addedPropsMapInSandbox
```
> :bug:  fix sandbox restore sequence

- package.json
close https://github.com/umijs/qiankun/issues/157
> :poop: set @types/vfile-message to a special version as it removed after 2.0

- README.md
> fix: readme.md misspelled words

- src/sandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/175)
> :bug: avoid who using window.window to escape the sandbox environment to touch the really window

- examples/react15/index.html
- examples/react15/index.js
- examples/react15/package.json
- package.json
- src/hijackers/dynamicHeadAppend.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/177)
> :bug: invoke the callback of dynamic script after script complete

- .travis.yml
- examples/react15/index.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/191)
> :beers: remove the unusable example code

- src/sandbox.ts
主要是解决 `window.top` 的问题：
1. `window.top` 的`configurable` 是 false，所以直接 proxy window 行不通，可以通过 proxy 一个空对象，然后各个 trap 里直接调用 window 来解决，这个改动风险未知，需要 review
2. 有的脚本用 `window.top !== window` 来判断是否是内嵌页面，所以需要在沙盒内将 `window.top` 的行为和正常情况一样，即`window.proxy.top === window.proxy`
> fix(sandbox): fake window.top in proxy get trap

- src/sandbox.ts
see https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constants.js#L12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/196)
> :bug: trap in operator at window

- src/hijackers/dynamicHeadAppend.ts
close https://github.com/umijs/qiankun/issues/194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/195)
> :bug: fix the security issue with cssRules

- src/index.ts
> modify lifycycle comment

- src/hijackers/publicPath.ts
see https://github.com/umijs/umi-plugin-qiankun/pull/49#discussion_r361473040
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/212)
> :bug: fix the undefined bug of publicPath with umi plugin

- src/prefetch.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/211)
> :zap: disable prefetch while with a slow network

- examples/vue/src/main.js
- examples/vue/vue.config.js
- upgrade vue example to make  it easier to start a new vue project
> :pencil: upgrade vue example

- src/sandbox.ts
> :bug: fix Proxy handler.set (#222)

- examples/main/index.js
- examples/main/package.json
close https://github.com/umijs/qiankun/issues/224
> :memo: upgrade demo

- src/prefetch.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/228)
> :sparkles: disable prefetch with mobile device or slow network

- examples/vue/src/main.js
- examples/vue/src/views/Home.vue
close https://github.com/umijs/qiankun/issues/217
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/237)
> :bug: fix vue demo live public path issue

- now.json
- package.json
> chore: site now

- docs/.vuepress/config.js
- now.json
> fix: site deploy base in now build

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/243)
> :memo: simplify README.md

- .prettierignore
- docs/faq/README.md
- docs/zh/faq/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/245)
> :memo: update doc

- docs/faq/README.md
- docs/zh/faq/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/258)
> :memo: update faq of runtime publicPath

- examples/react15/dynamic.css
- examples/react15/index.html
- examples/react15/index.js
- examples/react15/public-path.js
- src/hijackers/dynamicAppend.ts
- src/hijackers/index.ts
- src/interfaces.ts
- src/prefetch.ts
- src/register.ts
- src/utils.ts
resolve https://github.com/umijs/qiankun/issues/187
应用外层再包裹一个带唯一 id 的 div，动态添加的样式也 append 到这个容器里，而不是 append 到 head
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/257)
> :bug: fix the dynamic insert stylesheet order issue

- docs/guide/getting-started.md
- docs/zh/guide/getting-started.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/265)
> :memo: polish doc

- package.json
ref https://github.com/kuitos/import-html-entry/releases/tag/v1.4.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/267)
> :arrow_up: upgrade import-html-entry

- package.json
- src/prefetch.ts
- src/register.ts
- src/utils.ts
目前有用户使用了未开放的 getTemplate api
ref https://github.com/kuitos/import-html-entry/pull/27
resolve https://github.com/umijs/qiankun/issues/274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/275)
> :sparkles: support compose the custom getTemplate config

- src/hijackers/dynamicHeadAppend.ts
- src/hijackers/index.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/277)
> :bug: avoid hijacking element appending except html head

- README.md
Added better Getting started instructions in README
> Update README.md with clear Getting started instructions

- src/hijackers/dynamicHeadAppend.ts
resolve https://github.com/umijs/qiankun/issues/279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/282)
> :bug: fix the bug that dynamic style are appending to document.head while app rebuilding

- examples/main/index.js
> :bug: visit vue app demo directly

- examples/vue/src/views/About.vue
- src/hijackers/dynamicHeadAppend.ts
- src/hijackers/index.ts
resolve https://github.com/umijs/qiankun/issues/285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/287)
> :bug: dynamic stylesheet injection will miss after the second rebuilding

- src/addons/runtimePublicPath.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/291)
> :bug: public path lifecycle adjust

- src/effects.ts
resolve https://github.com/umijs/qiankun/issues/292
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/294)
> :checkered_flag: compatible with ie which not support addEventListener with once option

- docs/faq/README.md
- [] `npm test` passes
- [] tests are included
- [] commit message follows commit guidelines
- Fix a typo in English document.
> :tada: fix typo

- docs/api/README.md
- docs/zh/api/README.md
- docs/zh/faq/README.md
resolve https://github.com/umijs/qiankun/issues/310
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/316)
> :pencil: update faq for hijacked script blocking solution

- docs/faq/README.md
- docs/guide/getting-started.md
- docs/zh/faq/README.md
- docs/zh/guide/getting-started.md
- examples/purehtml/index.html
> :pencil: replace relatively resources

- now.json
> :pencil: v1 site

- package.json
- src/index.ts
- src/register.ts
- src/sandbox/index.ts
- src/sandbox/patchers/dynamicHeadAppend.ts
- src/sandbox/patchers/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/355)
> ✨ simplify the duplicate loader configuration

- docs/api/README.md
- docs/zh/api/README.md
- src/register.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/357)
> :pencil: upgrade doc

- docs/api/README.md
- docs/zh/api/README.md
- src/interfaces.ts
- src/prefetch.ts
- src/register.ts
感谢您贡献代码。请确认下列 checklist 的完成情况。
Bug 修复和新功能必须包含测试。
Contributors guide: https://github.com/umijs/qiankun/blob/master/CONTRIBUTING.md
-->
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/358)
> 🎨 refactor prefetch

- package.json
- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/index.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/proxySandbox.ts
- any feature?
- resolve https://github.com/umijs/qiankun/issues/365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/371)
> :bug: fix the proxy sandbox issue

- src/sandbox/__tests__/proxySandbox.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/374)
> :green_heart: add unit-test for proxy sandbox

- package.json
> :arrow_up: upgrade single-spa@5

- .eslintrc.js
- package.json
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/375)
> :arrow_up: upgrade fabric

- package.json
- src/apis.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/387)
> :arrow_up: follow the latest single-spa api

- src/interfaces.ts
- src/loader.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/388)
> :label: upgrade type definition

- docs/faq/README.md
- docs/zh/faq/README.md
- examples/purehtml/entry.js
- examples/purehtml/index.html
- close https://github.com/umijs/qiankun/issues/393
> :pencil: complete purehtml demo

- docs/.vuepress/config.js
- docs/README.md
- docs/zh/README.md
close https://github.com/umijs/qiankun/issues/410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/411)
> :memo: add 1.x links

- docs/faq/README.md
- docs/zh/faq/README.md
add error explain and fix options about `vue-router`
> :pencil: update faq.md about vue-router error

- examples/react16/src/index.js
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/413)
> :drunk: demo fixing

- src/index.ts
- src/interfaces.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/414)
> :sparkles: export prefetchApps function

- src/interfaces.ts
- src/loader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/415)
> :label: polish typing

- examples/react16/src/index.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/419)
> :memo: fix demo for stand-alone running

- examples/main/index.js
- src/apis.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/425)
> :alien: update jsSandbox -> sandbox

- docs/faq/README.md
- docs/zh/faq/README.md
- examples/purehtml/entry.js
- examples/purehtml/index.html
- cherry pick from v2.x https://github.com/umijs/qiankun/commit/e484165fe7f3eda44ae83c4148381423dc786931
> :pencil: complete purehtml demo (#402)

- examples/main/multiple.html
- examples/main/multiple.js
- examples/main/package.json
- examples/react15/index.js
- examples/vue/src/main.js
- examples/vue/vue.config.js
- package.json
- src/sandbox/common.ts
- src/sandbox/index.ts
- src/sandbox/patchers/dynamicHeadAppend.ts
- src/sandbox/patchers/index.ts
- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/427)
> ✨ support dynamic append in multiple mode

- src/sandbox/patchers/timer.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/435)
> :bug: revert timer lazy clear logic

- docs/api/README.md
- docs/zh/api/README.md
- src/__tests__/globalState.test.ts
- src/globalState.ts
- update api doc for globalState
> memo: update api doc for globalState

- docs/README.md
- docs/zh/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/446)
> :memo: upgrade home page doc

- src/apis.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/448)
> :bug: set default value of register mode

- docs/zh/api/README.md
- examples/main/index.js
- src/apis.ts
- src/index.ts
- src/interfaces.ts
- src/prefetch.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/449)
> :sparkles: update prefetchApps api and docs

- src/loader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/471)
> :bug: fix the app instance count error

- src/globalState.ts
To correct a clerical mistake.
- any feature?
> fix: to correct a clerical mistake.

- src/loader.ts
resolve https://github.com/umijs/qiankun/issues/477
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/488)
> :bug: support update lifecycle export

- examples/react16/.rescriptsrc.js
resolve https://github.com/umijs/qiankun/pull/482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/489)
> :bug: set the cra globalObject setting to window to avoid multiple sandbox escaping

- docs/api/README.md
- docs/zh/api/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/492)
> :pencil2: type setting

- src/sandbox/patchers/index.ts
ref #497
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/498)
> :sparkles: open the dynamic head append patch while bootstrapping

- src/loader.ts
- src/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/495)
> :loud_sound: optimize log and not assert the container must be exist after micro app unmounted

- examples/main/render/VueRender.js
Signed-off-by: lizhiwei <0049003294@znv.com>
- any feature?
> demo中主应用使用Vue技术栈渲染子应用，根元素ID错误。

- src/loader.ts
appInstanceId 后缀使用时间戳保证多个应用同时引入一个微应用时样式表不会挂载错误
- resolve #472
> fix: guarantee the uniqueness of appInstanceId

- examples/main/multiple.js
- examples/vue/vue.config.js
- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- any feature?
- close https://github.com/umijs/qiankun/issues/514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/511)
> :bug: never rewrite eval function to keep it scope in a right place

- src/sandbox/patchers/dynamicHeadAppend.ts
- [ x ] `npm test` passes
- close #420
> rewrite insertBefore  issues #420

- src/sandbox/noise/systemjs.ts
- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/520)
> :sparkles: write System back to global window

- src/sandbox/patchers/dynamicHeadAppend.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/521)
> :bug: avoiding intercept the master dynamic style appending

- src/loader.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/533)
> :checkered_flag: detect and warning if current runtime not support shadow dom

- src/sandbox/patchers/dynamicHeadAppend.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/534)
> :bug: only execute dynamic append script while it invoked by micro app

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/544)
> :checkered_flag: fix the sandbox issue in FF/Safari

- docs/api/README.md
- docs/zh/api/README.md
- examples/main/index.js
- examples/main/render/ReactRender.jsx
- src/apis.ts
- src/interfaces.ts
- src/loader.ts
- src/sandbox/patchers/dynamicHeadAppend.ts
- src/utils.ts
resolve #536
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/537)
> :sparkles: add loader function for registerMicroApps api

- src/globalState.ts
> fix annotation incorrect

- docs/api/README.md
- docs/zh/api/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/572)
> :memo: update api example

- examples/react16/src/components/HelloModal.js
- src/sandbox/patchers/UIEvent.ts
- src/sandbox/patchers/__tests__/UIEvent.test.ts
- src/sandbox/patchers/index.ts
- tsconfig.json
- close https://github.com/umijs/qiankun/issues/570
> :bug: rewrite ProxyWindow in UIEvent

- src/sandbox/patchers/UIEvent.ts
> :bug: fix MouseEvent prototype

- src/sandbox/patchers/UIEvent.ts
- src/sandbox/patchers/__tests__/UIEvent.test.ts
- tsconfig.json
- ts compile to es6 
- add error case for UIEvent
> :white_check_mark: ts compile to es6 & add MouseEvent error case

- .github/workflows/now.yml
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/598)
> :green_heart: fix now deployment error

- .umirc.ts
> docs: fix site logo display

- .github/workflows/now.yml
感谢您贡献代码。请确认下列 checklist 的完成情况。
Bug 修复和新功能必须包含测试。
Contributors guide: https://github.com/umijs/qiankun/blob/master/CONTRIBUTING.md
-->
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/599)
> :green_heart: fix now deployment

- .github/workflows/now.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/600)
> :green_heart: fix ci

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/594)
> :bug: define the property to original target to avoid illegal invocation error

- src/loader.ts
resolve https://github.com/umijs/qiankun/issues/612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/614)
> :bug: fix performance mark not existed issue while next mounting

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/624)
> :green_heart: remove duplicated dependency

- examples/main/index.js
- examples/main/render/VueRender.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/622)
> :memo: upgrade vue demo

- .github/workflows/now.yml
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/626)
> :green_heart: last time I fix it

- src/sandbox/patchers/UIEvent.ts
- src/sandbox/patchers/__tests__/UIEvent.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/639)
> :bug: make ui event patcher compatible with safari/firefox

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
- src/sandbox/proxySandbox.ts
- src/utils.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/641)
> :bug: compatible with safari/firefox

- src/sandbox/patchers/dynamicHeadAppend.ts
resolve #642 
resolve #643
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/645)
> :bug: just counting dynamic head append while mounting phase

- src/sandbox/patchers/dynamicHeadAppend.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/653)
> :bug: appWrapperGetter maybe not be able to get the element while not in sandbox

- src/addons/engineFlag.ts
- src/sandbox/patchers/UIEvent.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/656)
> :rotating_light: remove lint warning

- src/apis.ts
- src/interfaces.ts
- src/loader.ts
- loadMicroApp 增加 lifeCycle 参数
- LifeCycleFn<T> 增加 global 参数（代理沙箱下代表沙箱环境，否则 fallback window）
TODO：API 文档更新
> :sparkles: loadMicroApp support lifeCycle

- .umirc.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/658)
> :pencil: fix site publicPath issue

- examples/vue/src/main.js
- close https://github.com/umijs/qiankun/674
> 🐛fix vue demo memory leak

- docs/api/README.md
- src/__tests__/globalState.test.ts
- src/globalState.ts
修改./src/globalState.ts文件中关于global的单词拼写
> modify variables spelling

- src/sandbox/patchers/dynamicAppend.ts
现在的逻辑里，singular true 模式下，动态插入的 script 会由于 invokedByMicroApp 判断为 false 导致沙箱逃逸
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/682)
> :bug: fix the dynamic append script not be managed by qiankun while in singular mode

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/687)
> :alien: lock eslint version temporary via https://github.com/airbnb/javascript/issues/2245

- docs/README.md
- docs/README.zh.md
resolve https://github.com/umijs/qiankun/issues/686
- any feature?
> :memo: use new dingtalk group

- docs/README.md
- docs/README.zh.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/693)
> :memo: update README.md

- src/globalState.ts
> Fix potential bug using "in" operator

- .github/ISSUE_TEMPLATE/bug_report_cn.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/708)
> :memo: update issue template

- docs/faq/README.md
- docs/faq/README.zh.md
- solve `Here is no "fetch" on the window env, you need to polyfill it`
> :pencil: polyfill fetch

- .eslintrc.js
- package.json
- src/sandbox/__tests__/utils.test.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/723)
> :alien: fix eslint error

- .github/workflows/contributors.yml
- README.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/725)
> :busts_in_silhouette: adding contributors bot

- src/sandbox/common.ts
- src/sandbox/patchers/dynamicAppend.ts
- src/sandbox/proxySandbox.ts
- [x ] `npm test` passes
- fix memory leak issue
- close https://github.com/umijs/qiankun/issues/706
> memory leak issue

- docs/api/README.zh.md
- src/sandbox/__tests__/utils.test.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/731)
> :memo: type setting

- src/sandbox/__tests__/utils.test.ts
- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/css.ts
- Adjust the rule when rewriting root level selector and close https://github.com/umijs/qiankun/issues/737
> :bug: fix incorrect css selector rewriting

- docs/api/README.md
- docs/api/README.zh.md
> :pencil2: fix doc format 

- docs/api/README.md
- docs/zh/api/README.md
- src/hijackers/dynamicHeadAppend.ts
- src/interfaces.ts
- src/register.ts
- src/utils.ts
同步 qiankun@2.x 更改 https://github.com/umijs/qiankun/pull/747
> :sparkles: excludeAssetFilter

- src/hijackers/dynamicHeadAppend.ts
- src/utils.ts
> :bug: exclude asset filter default

- src/sandbox/patchers/dynamicAppend.ts
> :bug: excludeAssetFilter link src to href

- src/hijackers/dynamicHeadAppend.ts
> :pencil2: typo execScriptsOpt

- docs/api/README.md
- docs/api/README.zh.md
- docs/faq/README.md
- docs/faq/README.zh.md
> :pencil: IE guide

- docs/faq/README.md
- docs/faq/README.zh.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/762)
> 📝 fix markdown which been escaped

- docs/faq/README.md
- docs/faq/README.zh.md
> :pencil: target blank

- docs/api/README.md
- docs/api/README.zh.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/767)
> 📝 replenish api doc

- docs/faq/README.md
- docs/faq/README.zh.md
close https://github.com/umijs/qiankun/issues/793
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/795)
> :memo: ie doc

- src/sandbox/patchers/css.ts
> :memo: fix typo

- src/__tests__/utils.test.ts
- src/loader.ts
- src/utils.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/798)
> ✨add data-name attr to template

- README.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/803)
> 📝 update README.md

- examples/main/index.html
- examples/main/multiple.html
- examples/main/package.json
- examples/main/webpack.config.js
- package.json
- src/sandbox/patchers/__tests__/interval.test.ts
- src/sandbox/patchers/index.ts
- src/sandbox/patchers/interval.ts
- src/sandbox/patchers/windowListener.ts
close https://github.com/umijs/qiankun/issues/52
close https://github.com/umijs/qiankun/issues/40
1. 使用 webpack 替换 parcel
2. 修复主应用 interval 会被清理的问题
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/804)
> 🐛 distinguish master and slave in patcher

- src/sandbox/proxySandbox.ts
> :bug: remove useless type assertion

- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/817)
> 🤖 compatible with some android browser

- .github/workflows/release-notify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/818)
> 👷 add more release notification robot

- examples/main/webpack.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/821)
> 📝 fix main example webpack config

- src/prefetch.ts
- 优化：去掉 prefetch 的移动端的限制
- close https://github.com/umijs/qiankun/issues/831
> 优化：去掉 prefetch 的移动端的限制

- src/sandbox/legacy/sandbox.ts
- src/sandbox/proxySandbox.ts
- close https://github.com/umijs/qiankun/issues/839
> :bug: fix the sandboxRunning flag always be true due to closure. (#839)

- src/prefetch.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/843)
> 🐛 define the slow network with wifi and ethernet negative assertion

- examples/angular9/src/main.qiankun.ts
- any feature?
- close https://github.com/umijs/qiankun/issues/781
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/848)
> 📝 fix angular example

- examples/main/webpack.config.js
> 📝 fix multiple demo

- docs/api/README.zh.md
remove useless character in readme.
> 📝 remove useless character

- docs/api/README.md
- docs/api/README.zh.md
- src/prefetch.ts
- any feature? 无，文档修正
- close 无
> doc：文档修正，生命周期函数需要返回 Promise

- src/sandbox/legacy/sandbox.ts
- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/864)
> ✨ add window.parent support

- docs/api/README.zh.md
> doc: remove redundant words

- package.json
- src/sandbox/patchers/dynamicAppend.ts
ref https://github.com/kuitos/import-html-entry/pull/51
- any feature?
> 🐛 use callback way instead while executing dynamic script to guarantee the onload event fired as soon as possible

- examples/main/package.json
> 使用 cross-env 兼容 windows 系统获取 process.env.MODE

- .fatherrc.js
- src/sandbox/snapshotSandbox.ts
- any feature?
- close https://github.com/umijs/qiankun/issues/877
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/883)
> 🐛 fix snapshot sandbox will never truly active issue

- docs/faq/README.md
- docs/faq/README.zh.md
- any feature?
- close https://github.com/umijs/qiankun/issues/632
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/891)
> 📝 add browser history mode faq

- src/sandbox/patchers/css.ts
https://github.com/umijs/qiankun/blob/f2f19e99a80beb89f05803d70259784acc9ec904/src/sandbox/patchers/css.ts#L138
这行正则在 IE 里会有语法问题
> :bug: fix regex syntax

- src/sandbox/patchers/dynamicAppend.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/900)
> 🐛 fix dynamic append script with excludeAssetsFilter issue

- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/css.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/923)
> 🐛 lazy init ScopedCSS to support referenced by html head script block

- docs/api/README.md
- docs/api/README.zh.md
- package.json
- 完善 entry 的说明
- 修正 getPublicPath 的说明
- 补充 ignore 的说明
> doc: supplement and improve api documentation

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/953)
> 🐛 lazy added non-configurable props should be reported as configurable to avoid TypeError

- package.json
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/974)
> ⏫ upgrade dumi to beta version

- src/sandbox/patchers/dynamicAppend.ts
- close https://github.com/umijs/qiankun/issues/968
- close https://github.com/umijs/qiankun/issues/951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/975)
> 🐛 fix the exception while removing a dynamic appending script in a micro app

- src/sandbox/common.ts
- close #748
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/977)
> 🐛 copy function prototype if it had while we create a new function using bind

- src/prefetch.ts
resolve https://github.com/umijs/qiankun/issues/787
resolve https://github.com/umijs/qiankun/issues/844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/980)
> 🐛 just prefetch the apps which not loaded, rather than the loading or loaded error ones

- docs/faq/README.md
- docs/faq/README.zh.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/983)
> 📝 add config entry faq doc

- package.json
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/984)
> ⏫ upgrade single-spa to latest version

- src/loader.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/987)
> ♻️ refactor some variable name

- docs/faq/README.md
- docs/faq/README.zh.md
> doc: fix the problem of font file loading failure

- src/sandbox/common.ts
- src/sandbox/patchers/dynamicAppend.ts
- src/utils.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/978)
> ⚡️ optimize sandbox performance

- docs/api/README.md
- docs/api/README.zh.md
> 📝fix docs details

- src/__tests__/utils.test.ts
- src/utils.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/991)
> 🐛 xpath return undefined while the dom have not append to document yet

- docs/faq/README.md
- docs/faq/README.zh.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/998)
> 📝 polish antd prefix doc

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1002)
> ⚡️ use WeakMap to instead symbol

- .prettierignore
- package.json
- src/apis.ts
- src/loader.ts
- src/prefetch.ts
- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/index.ts
- src/sandbox/patchers/css.ts
- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forLooseSandbox.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/patchers/historyListener.ts
- src/sandbox/patchers/index.ts
- src/sandbox/patchers/interval.ts
- src/sandbox/patchers/windowListener.ts
- src/sandbox/proxySandbox.ts
- src/sandbox/snapshotSandbox.ts
- src/utils.ts
> 🎨 format code

- src/loader.ts
resolve https://github.com/umijs/qiankun/issues/979
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1006)
> 🐛 re-process the internal style in element after app remount

- src/sandbox/patchers/dynamicAppend/common.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1007)
> 🐛 manual invoke dynamic link load event

- src/utils.ts
- any feature?
- close https://github.com/umijs/qiankun/issues/1012
> fix: Ie does not support document.contains

- examples/main/multiple.js
- src/apis.ts
- src/interfaces.ts
- src/sandbox/patchers/dynamicAppend/common.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1018)
> ✨ add internal force cache config

- src/loader.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1021)
> 🐛 should use the new element reference while in cache scenario

- examples/vue3/src/main.js
> fix vue3.0 example

- examples/react16/src/components/HelloModal.js
- any feature?
NO.
NO.
Just fix the boring warning when running the examples.
> fix example linting warning

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1053)
> 🐛 fix nullish bug in proxy sandbox

- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forLooseSandbox.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- any feature?
- close https://github.com/umijs/qiankun/issues/1032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1054)
> 🐛 dynamicStyleElement array should not be clear after remount

- src/interfaces.ts
- src/loader.ts
- src/sandbox/index.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/proxySandbox.ts
see https://github.com/umijs/qiankun/issues/485#issuecomment-617677419
Object iteration order was certainly in es2015 spec, but unfortunately not all the browser did it in fact.
- any feature?
- close https://github.com/umijs/qiankun/issues/1013
- close https://github.com/umijs/qiankun/issues/770
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1056)
> ✨ record latest set property for lifecycle fallback resolving in some incompatible scenario

- .travis.yml
- package.json
- src/interfaces.ts
- src/sandbox/proxySandbox.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1057)
> ✨ add qiankun runtime variable

- src/sandbox/proxySandbox.ts
- close https://github.com/umijs/qiankun/issues/1043
> fix uniq function bug with edge

- package.json
[This change](https://github.com/single-spa/single-spa/pull/657) of single-spa leads to the main application routing changes not be notified to micro apps.
The reason is that umi micro app never called the start method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1071)
> 📌 lock single-spa version to 5.8.1 temporary

- src/sandbox/legacy/sandbox.ts
- any feature?
主应用 legacySandbox，子应用 proxySandbox 的嵌套情况会出错
> :bug: proxy getOwnPropertyDescriptor in legacySandbox

- package.json
- any feature?
- close https://github.com/umijs/qiankun/issues/1090
> 📌 lock @types/react version to avoid conflict

- package.json
- src/utils.ts
> 👽 fix typescript typing error

- src/sandbox/common.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1134)
> ⚡️ avoid duplicate value check to improve performance

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
resolve https://github.com/umijs/qiankun/issues/1121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1136)
> 🏁 compatible with old browser

- src/sandbox/legacy/sandbox.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1156)
> 🐛 sync getOwnPropertyDescriptor trap logic of legacy sandbox from proxy sandbox

- docs/README.md
- docs/README.zh.md
> 📝 use new dingtalk group

- examples/main/index.js
如 issue 中描述，其实 import 方式  和 <script> 方式是一样的，引入的是同一份文件，差别在于引入位置，将zone.js放到qiankun之前引入即可
- any feature?
- close https://github.com/umijs/qiankun/issues/1157
> 🐛 fix angular demo

- src/addons/engineFlag.ts
- src/addons/index.ts
- src/addons/runtimePublicPath.ts
- src/apis.ts
- src/globalState.ts
- src/interfaces.ts
- src/loader.ts
- src/prefetch.ts
- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
- src/sandbox/index.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/patchers/dynamicAppend/forLooseSandbox.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/patchers/index.ts
- src/sandbox/patchers/interval.ts
- src/sandbox/proxySandbox.ts
- src/sandbox/snapshotSandbox.ts
- src/utils.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1179)
> 🚨 upgrade to follow eslint new rules

- package.json
- src/sandbox/legacy/sandbox.ts
- src/sandbox/snapshotSandbox.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1180)
> 👷 add yarn build to ci

- .fatherrc.js
- typings/index.d.ts
- any feature? 新增 umd 方式打包
- close https://github.com/umijs/qiankun/issues/1147
> feat: support for umd build

- package.json
- src/sandbox/proxySandbox.ts
- resolve https://github.com/umijs/qiankun/issues/1208
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1210)
> 🐛 fix the active sandbox count issue

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1246)
> ✨ hijack accessing window object with globalThis keyword

- docs/guide/getting-started.md
- docs/guide/getting-started.zh.md
This link was added in #559 and its content was removed in #1167 . So I updated this link to the purehtml example.
> docs: update the link of example without bundler

- src/sandbox/proxySandbox.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1292)
> 🚨 fix tsc error

- package.json
- src/interfaces.ts
- src/register.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1300)
> ⏫ unlock import-html-entry version

- .umirc.ts
Enable the full-new logo, and customize hero background.
Preview:
> 📝 enable new logo & hero

- .umirc.ts
- package.json
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1308)
> 📢 add recruitment ad

- docs/faq/README.md
- docs/faq/README.zh.md
- any feature?
- close https://github.com/umijs/qiankun/pull/1256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1328)
> 📝 add faq about how to enable cors request with custom fetch configuration

- docs/faq/README.zh.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1329)
> 📝 add umi plugin usage about credential cookie setting

- examples/vue3/src/main.js
> vue3 WebHistory  must be destroyed

- docs/api/README.md
- docs/api/README.zh.md
props 里 name 是保留字，不能自定义
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1345)
> 📝 fix doc demo mistake

- docs/README.md
- docs/README.zh.md
> 📝 update new dingtalk group

- src/prefetch.ts
- src/sandbox/__tests__/common.test.ts
- src/sandbox/common.ts
- src/utils.ts
resolved https://github.com/umijs/qiankun/issues/1174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1381)
> 🐛 constructable checking should not be cached if the function prototype function was added after first running

- examples/vue3/package.json
1.只是修改锁定依赖即可
2.npm test测试通过
3.eslint校验通过
4.建议加上lock,这个版本适配问题比较花费时间
resolved #1352 
resolved #1382
> fixbug1352，适配vue3 并修改代码缩进

- examples/vue3/package.json
package.json 里面多余了一个逗号
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1292)
> remove extra comma in vue3/package.json

- docs/api/README.md
> 📝 fix: replace Chinese character to English in README.md

- src/sandbox/__tests__/common.test.ts
- src/sandbox/common.ts
- src/utils.ts
- close https://github.com/umijs/qiankun/issues/1121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1408)
> 🏁 fix that it might throw a TypeError about reassign a readonly property error meesage in Safari

- .github/workflows/release-notify.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1413)
> 📢 add fourth ding group notification

- .github/workflows/ci.yml
- .github/workflows/now.yml
- .github/workflows/publish-1.x.yml
- .github/workflows/publish-latest.yml
- .github/workflows/publish-next.yml
- .github/workflows/release-notify.yml
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1416)
> 💚 fix publish

- .github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1417)
> 💚 fix push action

- .github/workflows/github-pages.yml
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1418)
> 👷 add gh-pages action

- README.md
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1422)
> 👷 use new github actions badge

- docs/README.md
- docs/README.zh.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1427)
> 📝 move community from issues to discussions

- README.md
Add logo for README.md, preview url: https://github.com/umijs/qiankun/blob/PeachScript-patch-1/README.md
> docs: add logo for README.md

- src/globalState.ts
> pref: remove meaningless deepclone

- .github/workflows/issue-close-inactive.yml
- .github/workflows/issue-close-require.yml
> 👷 add inactive issue close action

- .github/workflows/issue-close-inactive.yml
> 👷 add inactive labeled action

- src/loader.ts
> fix(#1491): disable strictGlobal if sandbox=false

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
> ✅ add window reference binding test

- docs/README.md
- docs/README.zh.md
> 📝 update dingtalk group QR Code

- src/sandbox/__tests__/proxySandbox.test.ts
ref https://github.com/umijs/qiankun/pull/1518#discussion_r656198011
> ✅ fix test case about window reference binding

- docs/cookbook/README.zh.md
- docs/guide/tutorial.md
- docs/guide/tutorial.zh.md
> 📝 fix some mistake

- .github/workflows/emoji-helper.yml
> ci: add emoji helper

- src/sandbox/__tests__/common.test.ts
- src/sandbox/common.ts
- close https://github.com/umijs/qiankun/issues/1595
> 🐛 function should return the same reference while it always bindable

- src/sandbox/common.ts
- src/sandbox/proxySandbox.ts
- fix https://github.com/umijs/qiankun/issues/1617
> ⚡️ fix the performance issue in sandbox

- src/apis.ts
- src/loader.ts
- close https://github.com/umijs/qiankun/issues/1089
> 🐛 keep the lifecycle execution order while multiple apps mounting on the same container parallelly

- src/__tests__/utils.test.ts
- src/interfaces.ts
- src/sandbox/proxySandbox.ts
- src/utils.ts
- close https://github.com/umijs/qiankun/issues/1628
> ⚡️reduce the invocation times with next tick in sandbox to make qiankun performance in control

- src/__tests__/utils.test.ts
- src/sandbox/patchers/windowListener.ts
- src/sandbox/proxySandbox.ts
- src/utils.ts
> ✨ hijack document event listener and destroy it after unmount

- src/sandbox/patchers/windowListener.ts
> chore: revert document event hijacking

- src/apis.ts
bigfish h5的Promsie polyfill没有实现finally()，兼容下。
> feat: promise.finally compat

- src/prefetch.ts
> 🏷 upgrade typing to follow latest ts version

- src/interfaces.ts
- src/loader.ts
- src/sandbox/index.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/proxySandbox.ts
ref https://github.com/umijs/plugins/pull/714
Made global context can be specified
> ✨ support nest sandbox scenario

- docs/api/README.md
- docs/api/README.zh.md
> refactor(docs/api): correct spelling errors in code examples

- docs/faq/README.md
> feat: 修改英文文档

- src/apis.ts
> ✨ add `autoStart` config to `loadMicroApp`

- src/__tests__/utils.test.ts
- src/loader.ts
- src/utils.ts
> ✨ use new unique instance name generator

- src/__tests__/utils.test.ts
- src/loader.ts
- src/utils.ts
> 🐛 app instance id generator compatible with nested sandbox

- package.json
> 💚  fix build-error caused by react types

- README.md
> docs: add dumi tag

- examples/vue3/src/main.js
> fix: 修复vue3案例中，main.js文件中，bootstrap函数中，console.log打印出来的不是绿色的内容的问题。

- src/sandbox/patchers/dynamicAppend/common.ts
> ✨ filter inexecutable script for dynamic import scenario

- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/css.ts
https://yuque.antfin-inc.com/bigfish/topics/2013
具体的bug内容见如上地址
> fix: CSS is processed many times in experimentalStyleIsolation

- src/__tests__/globalState.test.ts
- src/__tests__/utils.test.ts
- src/addons/index.ts
- src/sandbox/index.ts
- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/dynamicAppend/__tests__/common.test.ts
- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/proxySandbox.ts
- src/utils.ts
fix https://github.com/umijs/qiankun/issues/1271
> 🐛 simulate a micro app head element for dynamic appending styles

- docs/README.md
- docs/README.zh.md
- src/loader.ts
- any feature? 更新钉钉群8的二维码
- close https://github.com/umijs/qiankun/issues/2106
> 📝  update dingtalk group QR Code

- src/loader.ts
https://github.com/umijs/qiankun/pull/2107 修复ts检查导致打包失败的问题
> 💚 fix build-error caused by ts check

- examples/main/index.js
- examples/react15/index.js
- src/__tests__/utils.test.ts
- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/utils.ts
- src/version.ts
* compatible with non-standard html document
* removeChild might throw an exception while the container is not a parent of the node
* dynamic appended style element not be removed while micro app calling removeChild before it unmount
* compatible with scoped css feature
> 🐛 fix the simulated head issues

- src/sandbox/patchers/dynamicAppend/common.ts
> 🐛 avoid accidentally deleted for dynamic stylesheet

- src/sandbox/patchers/dynamicAppend/common.ts
As dynamic appended head script will be removed from qiankun head
> 🐛 dynamic head script should be append to qiankun head

- package.json
- src/interfaces.ts
- src/loader.ts
- src/sandbox/common.ts
- src/sandbox/index.ts
- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forLooseSandbox.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/patchers/index.ts
- src/sandbox/proxySandbox.ts
Use `sandbox: { speedy: true }` to enable this performance improvement.
ref https://github.com/kuitos/import-html-entry/pull/82
resolves #2035 
resolves #2008 
resolves #1980 
resolves #1944 
resolves #1555 
resolves #1320 
resolves #1223 
resolves #1175 
resolves #1110 
resolves #588
> ⚡️ add speedy mode for sandbox to improve performance

- docs/faq/README.md
- docs/faq/README.zh.md
The writing method in the example will cause repeated entry into the hook, causing a dead cycle
> docs[faq]: next() dead loop simple processing

- src/__tests__/utils.test.ts
- src/utils.ts
> 🐛 isPropertyReadonly support accessor assert

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- src/utils.ts
> ♻️ refactor the global whitelist recovery logic and fix the unit test

- docs/README.md
- docs/README.zh.md
- any feature? 更新钉钉9群的二维码，新增微信群二维码
> 📝 update dingtalk group 9 QR Code

- docs/faq/README.md
- docs/faq/README.zh.md
* resolves #2214
* resolves #2139
* resolves #2090
* resolves #1279
* resolves #1213
> 📝 add new faq about import-html-entry

- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/proxySandbox.ts
- close https://github.com/umijs/qiankun/issues/1689
> fix: 🐛 delete defineProperty to recover doc.currentScript

- src/__tests__/utils.test.ts
- src/utils.ts
> 🚚 rename data-sandbox-configuration to data-sandbox-cfg

- .fatherrc.js
- src/loader.ts
- src/sandbox/__tests__/proxySandbox.speedy.test.ts
- src/sandbox/common.ts
- src/sandbox/globals.ts
- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/proxySandbox.ts
* resolves: https://github.com/umijs/qiankun/issues/2398 
* ref: https://github.com/kuitos/import-html-entry/pull/87
- any feature?
> 🐛 compatible with legacy browser which not support globalThis in speedy mode

- package.json
> ⬆️ bump import-html-entry version

- src/interfaces.ts
- src/sandbox/common.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/patchers/dynamicAppend/forLooseSandbox.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/patchers/index.ts
- src/sandbox/proxySandbox.ts
- src/sandbox/snapshotSandbox.ts
* resolves https://github.com/umijs/qiankun/issues/2338
* resolves https://github.com/umijs/qiankun/issues/1929
- any feature?
> ✨patch sandbox document to aviod chaos of dynamic element appending when speedy mode enabled

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/utils.ts
* resolves https://github.com/umijs/qiankun/issues/2406
- any feature?
> 🐛 compatible with MutationObserver as document had been wrapped as a proxy

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
> 🧑‍💻not rebind a bounded function of document

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
> 🐛 speedy mode sandbox should compatible with element-ui popper

- .github/workflows/github-pages.yml
> 💚 fix github pages ci

- tsconfig.json
tsconfig.json#compilerOptions:
```json
{
"compilerOptions": {
"paths": {
"qiankun": ["./src"]
}
}
}
```
- any feature?
allow the name of qiankun to be searched by vscode or typescript
e.g. the keyword qiankun appears in the docs/README.md
```js
import { registerMicroApps, start } from 'qiankun';
```
once the qiankun added to the paths of the tsconfig.json#compilerOptions,
the package name qiankun would be allowed to be searched by vscode or typescript.
none
> feat: tsconfig.json - add paths qiankun -> src

- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- resolves https://github.com/umijs/qiankun/issues/1929#issuecomment-1483767829
> 🐛 compatible with overwritten appendChild by apps themselves

- src/sandbox/__tests__/proxySandbox.speedy.test.ts
- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
> 🐛 hasOwnProperty should work well with special [[This]] binding

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
avoid micro app accessing the global head element with document.querySelector
> ✨port document.querySelector('head') to qiankun head in micro app

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
> 🐛 document.head.removeChild should be hooked in sandbox

- src/sandbox/proxySandbox.ts
> 🐛 compatiable with react development for event rewrite scenarios

- examples/main/index.html
- examples/main/index.js
- examples/main/package.json
- examples/react15/App.jsx
- examples/react15/index.html
- examples/react15/webpack.config.js
- packages/loader/package.json
- packages/loader/src/index.ts
- packages/loader/src/writable-dom/index.ts
- packages/qiankun/src/loader.ts
- packages/sandbox/package.json
- packages/shared/package.json
- packages/shared/src/assets-transpilers/index.ts
- packages/shared/src/assets-transpilers/link.ts
- packages/shared/src/assets-transpilers/script.ts
- packages/shared/src/common.ts
- packages/shared/src/index.ts
- packages/shared/src/module-resolver/__tests__/index.ts
- packages/shared/src/module-resolver/index.ts
- packages/shared/src/typings.d.ts
- pnpm-lock.yaml
运行时基于依赖描述及 semver 动态决策子应用是否复用子应用依赖。
启动 examples 里 main 跟 react15 两个应用查看效果。
> ✨runtime dependecy reuse

- src/prefetch.ts
requestIdleCallback增加MessageChannel的垫片
> chore: requestIdleCallback add the polyfill of MessageChannel

- docs/faq/README.zh.md
> update: fix word error

- package.json
fixes https://github.com/umijs/qiankun/issues/2448
- any feature?
> fix: upgrade import-html-entry v1.14.6

- .eslintignore
> chore: test ci robot

- contributors.json
> chore: add new contributors :)

- package.json
- tsconfig.json
> ➖ remove unused ts importHelpers config

- docs/guide/getting-started.zh.md
> docs: 更新在webpack v5中变更的配置名称

- docs/faq/README.md
- docs/faq/README.zh.md
更正文档内容
- any feature?
- close 
https://github.com/umijs/qiankun/issues/2659
> docs: correct-document

- .eslintignore
- .github/workflows/ci.yml
- package.json
1. yarn => pnpm
2. upgrade gh actions actions/checkout@v2 => actions/checkout@v4
3. upgrade gh actions actions/setup-node@v2 => actions/setup-node@v3
4. test node version: 14.x, 16.x => lts/*, latest
- any feature?
> build: update gh action ci

- .changeset/long-flies-repair.md
- packages/sandbox/src/core/membrane/index.ts
- packages/sandbox/src/core/membrane/utils.ts
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- packages/sandbox/src/patchers/dynamicAppend/types.ts
- packages/sandbox/src/utils.ts
合并 master 上遗留的 commits
https://github.com/umijs/qiankun/compare/next...master
包括：
- https://github.com/umijs/qiankun/pull/2499
- https://github.com/umijs/qiankun/pull/2502
- https://github.com/umijs/qiankun/pull/2503
- https://github.com/umijs/qiankun/pull/2522
- https://github.com/umijs/qiankun/pull/2545
- https://github.com/umijs/qiankun/pull/2574
- https://github.com/umijs/qiankun/pull/2576
- https://github.com/umijs/qiankun/pull/2630
> 🔀 merge master

- .changeset/warm-chefs-chew.md
- packages/qiankun/.fatherrc.js
- packages/qiankun/src/core/loadApp.ts
- packages/qiankun/src/version.ts
> ✨ set data-name on micro app container

- .prettierignore
- any feature?
- refs: https://github.com/umijs/qiankun/pull/2723#issuecomment-1756699533
> chore: prettier ignore packages/*/package.json

- docs/README.md
- docs/README.zh.md
> 📝 update dingtalk group QR Code 10

- .changeset/selfish-lamps-thank.md
- packages/qiankun/src/core/loadApp.ts
由于在卸载前，已经把挂载节点的所有子元素全部移除，挂载节点本身不需要再设置为 null
================================
更新：继续保持设置为 null 的逻辑，修改后的逻辑为：在 mount 前，确保 container 存在
- close https://github.com/umijs/qiankun/issues/2735
> fix: remount-error

- .changeset/three-hornets-hammer.md
- packages/qiankun/src/core/loadApp.ts
- packages/qiankun/src/types.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- ref https://github.com/umijs/qiankun/pull/2751
> fix: should invoke getContainer method to get container every time to avoid reference misordering

- .eslintrc.cjs
这个包里面也有一些非ts的代码，单独配置一下。
- any feature?
> chore: eslint config for cjs

- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
不要将 tests 作为 workspace
- any feature?
> chore: update pnpm-workspace

- .changeset/red-students-run.md
- .eslintrc.cjs
- packages/loader/src/TagTransformStream.ts
- packages/qiankun/src/core/loadApp.ts
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- packages/ui-bindings/react/src/MicroApp.tsx
微应用在 remount 时会复用沙箱，但是此时 container DOM 的引用大概率是变了，所以需要沙箱里每次获取 container 的时候触发一次 getter 获取最新的引用，而不能在前置流程中缓存下来
> fix(sandbox): should get container from getter function while accessing

- .changeset/slow-timers-heal.md
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
> fix(sandbox): createElement hijack must be paired to avoid rewriting leak

- .changeset/silly-books-complain.md
- .eslintrc.cjs
- packages/sandbox/src/core/sandbox/index.ts
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- packages/sandbox/src/patchers/historyListener.ts
- packages/sandbox/src/patchers/interval.ts
- packages/sandbox/src/patchers/types.ts
- packages/sandbox/src/patchers/windowListener.ts
- resolves https://github.com/umijs/qiankun/issues/219
> feat(sandbox): micro app mounting should wait unit rebuilding link element loaded to avoid unstyleed content flash

- .changeset/hungry-needles-doubt.md
- packages/loader/src/index.ts
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/shared/src/assets-transpilers/script.ts
- packages/shared/src/index.ts
- packages/shared/src/script-queue/index.ts
- packages/shared/src/utils.ts
> feat: support defer scripts and keep the executing order to consist with browser

- .changeset/loud-teachers-develop.md
- packages/qiankun/src/core/loadApp.ts
> feat: enable sandbox by default

- examples/react15/webpack.config.js
> fix: react15 demo

- .changeset/yellow-frogs-marry.md
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
This reverts commit 62048537f855ebaf6bc5a1d364632712ff17428b.
> Revert "fix(sandbox): non-hijacking elements should be appended to global document (#2861)

- .changeset/clean-walls-hang.md
- packages/sandbox/src/core/membrane/index.ts
- packages/shared/src/fetch-utils/wrapFetchWithCache.ts
- packages/webpack-plugin/package.json
- pnpm-lock.yaml
cheerio  应该放在 dependencies 才能正常运行
> fix: cheerio move to dependencies

- .changeset/sweet-cars-protect.md
- packages/create-qiankun/package.json
package.json  add template for publish
> fix: adjust publish field

- src/sandbox/proxySandbox.ts
- [x ] tests are included
问题：这里的属性类型判断应该有点问题吧，在set handler 中是判断了类型，而 get handler 中则是字符串字面量？
修改点：修改了 ProxySandbox 中的 get handler 属性判断，与 set handler 保持一致
- any feature?
> fix: 修改 get handler 的属性类型判断
