- src/hijackers/timer.ts
- src/hijackers/windowListener.ts
splice the same reference would cause the listener traverse disordered, see 
https://github.com/umijs/qiankun/blob/9bdb48ab6b5867579c8d2a474e2a3b6a7c451562/src/hijackers/windowListener.ts#L25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/76)
> :bug: use a ref copy instead to avoid listener traverse disordered while splicing

- README.md
- examples/main/Framework.jsx
- examples/main/index.js
- package.json
- src/effects.ts
add runAfterFirstMounted effect hook, usually used for add tracking code.
```ts
import { runAfterFirstMounted } from 'qiankun';
runAfterFirstMounted(startGoogleAnalysis())
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/96)
> :sparkles: add runAfterFirstMounted effect hook

- .eslintrc.js
- .prettierignore
- .prettierrc.js
- package.json
- src/effects.ts
- src/hijackers/historyListener.ts
- src/hijackers/windowListener.ts
- src/index.ts
- src/sandbox.ts
- src/utils.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/101)
> :rotating_light: supplement lint config

- src/index.ts
1. 保证子应用脚本执行在 qiankun 框架启动之后
2. 移除 registerMicroApps 里的 fetch 配置
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/113)
> :bug: make sure the sub app execute after framework started

- src/index.ts
close https://github.com/kuitos/import-html-entry/pull/12
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/131)
> :sparkles: fallback to get exports from window[appName] while entry module exports not found

- src/hijackers/dynamicStylesheet.ts
- src/hijackers/index.ts
- src/hijackers/timer.ts
- src/hijackers/windowListener.ts
- src/sandbox.ts
针对 bootstrap 阶段添加的副作用 (如 style-loader 在应用 mount 前动态插入的样式) 的处理
close https://github.com/umijs/qiankun/issues/118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/129)
> :sparkles: hijack the dynamic stylesheet injection during development phase

- src/sandbox.ts
> If the following invariants are violated, the proxy will throw a TypeError:
> The value reported for a property must be the same as the value of the corresponding target object property if the target object property is a non-writable, non-configurable data property.
The value reported for a property must be undefined if the corresponding target object property is non-configurable accessor property that has undefined as its [[Get]] attribute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/176)
> :rewind: non-configurable variable could not be proxy

- docs/api/README.md
- docs/zh/api/README.md
- package.json
- src/errorHandler.ts
- src/index.ts
- resolve https://github.com/umijs/qiankun/issues/252 
- resolve https://github.com/umijs/qiankun/issues/160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/256)
> :sparkles: add global error handler

- src/hijackers/dynamicHeadAppend.ts
- src/hijackers/index.ts
- src/interfaces.ts
- src/register.ts
- src/sandbox.ts
Fixes  #341 
透传了`{fetch}` 参数对象，在子应用采用 dynamic import 时，使用 custom 的 fetch 方法
> :bug: dynamic import  with custom fetch

- .travis.yml
- package.json
- src/sandbox/patchers/__tests__/timer.test.ts
- src/sandbox/patchers/timer.ts
resolve https://github.com/umijs/qiankun/projects/2#card-34875468
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/360)
> :bug: fix the issue which an auto closed dialog with a timer would not be cleared after app unmounted

- src/apis.ts
- src/interfaces.ts
- src/loader.ts
- src/sandbox/index.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/423)
> 🎨 rename jsSandbox -> sandbox and refactor the internal sandbox api

- src/sandbox/patchers/dynamicHeadAppend.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/438)
> :bug: add the missing parameter for execScript

- examples/purehtml/index.html
script tag 放在了 body 外面
虽然是个小问题...
> Update script tag to be inside body

- src/globalState.ts
- src/loader.ts
缓存会导致 execScript 不会重新执行，这样会导致应用的沙箱拦截不到 loading 阶段的副作用
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/468)
> :bug: not cache the instance exports

- .eslintrc.js
- src/sandbox/patchers/dynamicHeadAppend.ts
多实例场景下由于不会确保后一个应用会在前一个 unmount 之后再 mount https://github.com/umijs/qiankun/blob/3bb406465d2d38417911e4bc47922a1c0fd0934a/src/loader.ts#L202
所以存在一种场景是 A 应用 mount 期间由于 B 应用 unmount 了，会将 A 应用对原型链的复写给移除掉，从而导致 A 应用后续的动态添加标签的行为失效。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/512)
> :bug: only release the head append prototype overwrite while all the apps are unmounted

- src/sandbox/patchers/dynamicHeadAppend.ts
Not write the document setting back to native document back will cause `Uncaught TypeError: Illegal invocation` exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/526)
> :bug: write document setting back to avoid illegal invocation

- package.json
import-html-entry 1.7.0 solved the problem that the micro app error stack is difficult to debug
resolve https://github.com/umijs/qiankun/issues/433
ref https://github.com/kuitos/import-html-entry/pull/37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/538)
> :arrow_up: upgrade import-html-entry to 1.7.0

- src/sandbox/patchers/dynamicHeadAppend.ts
bug fix - insertBefore will report an error when refChild is not a child node.
As shown below.
resolve https://github.com/umijs/qiankun/issues/554
> :bug: insertBefore will report an error

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/noise/systemjs.ts
- src/sandbox/proxySandbox.ts
发现没必要使用 updateValueMap 作为桥接，可以直接回写到 fakeWindow，这样也能避免诸如 Object.defineProperty 方式写入 proxy 的行为丢失
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/545)
> :sparkles: write value back to fake window to instead of value map

- src/addons/engineFlag.ts
- src/addons/index.ts
- src/apis.ts
子应用若自己也 import 了 qiankun 则无法通过 `__POWERED_BY_QIANKUN__` 判断自己是否是嵌入模式了，兼容有的应用又是子应用又是主应用的场景
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/595)
> :sparkles: inject qiankun engine flag to micro app rather than set it to native window

- src/sandbox/patchers/dynamicHeadAppend.ts
resolve #590 
dynamicHeadAppend.ts中insertBefore加入script处理逻辑
> feat: insertBefore加入script逻辑

- src/loader.ts
- src/utils.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/603)
> :sparkles: add performance timing log

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/proxySandbox.ts
- src/utils.ts
1. 使用 Symbol.unscopables 机制过滤某些高频的、不会被复写的原生属性的访问操作
2. 优化若干沙箱内的方法，保证尽可能高的调用性能
3. 修复 hasOwnProperty 和 bound function 在沙箱场景行为不符合预期的问题，从而避免触发不必要的 UI library rerender
ref https://github.com/umijs/qiankun/issues/588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/625)
> ⚡ optimize sandbox performance

- src/sandbox/index.ts
- src/sandbox/patchers/dynamicHeadAppend.ts
bootstrap patch 只会执行一次，但是 bootstrap freer function 每次 unmount 都会执行
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/652)
> :bug: bootstrapping patch just run once but freer may called repeatedly

- src/interfaces.ts
- src/sandbox/index.ts
- src/sandbox/legacy/sandbox.ts
- src/sandbox/patchers/UIEvent.ts
- src/sandbox/patchers/index.ts
- src/sandbox/proxySandbox.ts
- src/sandbox/snapshotSandbox.ts
- close https://github.com/umijs/qiankun/issues/701
> :sparkles: patch on demand

- docs/api/README.md
- docs/api/README.zh.md
- src/interfaces.ts
- src/loader.ts
- src/sandbox/__tests__/utils.test.ts
- src/sandbox/index.ts
- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/css.ts
- src/sandbox/patchers/dynamicAppend.ts
- src/sandbox/patchers/index.ts
- src/utils.ts
qiankun offered `strictStyleIsolation` already, but it is implemented by shadow-dom which may casue other problems, we may need a more generic way to support `css isolation`. 
With this PR, a experimental feature is added, if you start qiankun with following args:
``` typescript
start({
sandbox: {
experimentalStyleIsolation: true
}
})
```
the css style of sub app will be isolated by the runtime transformer, i.e. processor will add a specified attribute selector for every single css rule.
``` css
.app-main { ... }
↓ ↓ ↓
div[data-qiankun-react16] .app-main { ... }
↓ ↓ ↓
tag[data-qiankun-appname] sub-app-css-selector
```
@keyframes, @font-face, @import, @page
When option: experimentalStyleIsolation is true, all styles of sub app will be rewrite and qiankun will limit their scope of …
> feat: add runtime css transformer

- docs/faq/README.md
- docs/faq/README.zh.md
add a FAQ about Vue Router
<br>
Some background information：     
- I'm having some problems when  use vue router in qiankun. I hope I can share some of my experience with others.
- And this is my first contribution to qiankun,   **I am eager to get this merged** . Thx~ 
@kuitos
<br>
<br>
> docs: add vue router tips

- examples/angular9/package.json
- examples/angular9/src/main.qiankun.ts
for `"./@angular/platform-browser/platform-browser"' has no exported member 'ɵBrowserPlatformLocation'.`
resolve https://github.com/umijs/qiankun/issues/618
resolve https://github.com/umijs/qiankun/issues/678
resolve https://github.com/umijs/qiankun/issues/466
To fix follow error when run `yarn examples:start`
> chore: fix error angular error in example folder

- src/loader.ts
在手动使用 loadApp 的时候会出现 `new Date()` 返回相同值的情况，进而导致同一时间加载的应用被赋予相同 ID。添加了 `Math.random()`以确保即便在这种情况下也能为不同的应用返回不同的 ID。
> :bug: appInstanceId may not be unique

- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/css.ts
For `experimentalStyleIsolation` ability, to fix root selector replace bug, for example `selector:not(:root)` will be replaced with `selector:notdiv[data-qiankun=xxx])` rather than the correct reuslt `selector:not(div[data-qiankun=xxx])`.
> fix: selector patch when using :root with :not

- examples/react15/index.js
- examples/react16/src/index.js
- any feature?
- close https://github.com/umijs/qiankun/issues/810
> 修复react子应用图片加载失败问题

- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/css.ts
- Fix root selector rewrite bug when attr selector followed:
```css
html [type="button"] {}
/* will be rewrite by mistake */
type="button"] {}
/* right result with the next feature */
div[prefix] [type="button"] {}
```
- Support to transform all the grouping selector for style isolation (**Please CR carefully**):
```css
a,b,c {}
/* will be transform to */
div[prefix] a,div[prefix] b,div[prefix] c {}
/* rather than */
div[prefix] a,b,c {}
```
> feat: isolation for all the grouping selector

- src/sandbox/patchers/__tests__/css.test.ts
- src/sandbox/patchers/css.ts
- The remaining problem in #833 :
```css
html [type="button"] {}
/* will be rewrite by mistake */
type="button"] {}
/* right result with the next feature */
div[prefix] [type="button"] {}
```
- CSS styles will apply failed if app name contains some character:
```css
/* invalid rules */
div[data-qiankun=1f2a3n] {}
div[data-qiankun=http://] {}
/* valid rules */
div[data-qiankun="1f2a3n"] {}
div[data-qiankun="http://"] {}
```
So the quotes of attribute selector is required for a framework, reference: https://mathiasbynens.be/notes/unquoted-attribute-values
> fix: style isolation failed if app name contains some character

- src/addons/runtimePublicPath.ts
- src/loader.ts
- src/sandbox/index.ts
- src/sandbox/proxySandbox.ts
- src/sandbox/snapshotSandbox.ts
remount 时由于沙箱还未 active，导致在 addons 的 beforeMount 里的 global mutation 无法被沙箱记录
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/847)
> 🐛 record global mutation in addons while remounting

- package.json
- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
- src/sandbox/index.ts
- src/sandbox/patchers/dynamicAppend.ts
- src/sandbox/proxySandbox.ts
changelist:
1. 合并了 appendChild 和 insertBefore 方法的重写
2. 不再代理 document，改为重写 Document.prototype.createElement 并从 this 中确认当前沙箱身份
- resolve https://github.com/umijs/qiankun/issues/841
- resolve https://github.com/umijs/qiankun/issues/668
- resolve https://github.com/umijs/qiankun/issues/634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/846)
> 🐛 not proxy document anymore to avoid causing dom type checking exception

- src/prefetch.ts
完善isSlowNetwork方法的判断逻辑 -- effectiveType属性是使用[最近一次]的值,所以比如上一次是4g,当前是断网的话会判定为还是4g，从而再去做预加载操作，导致多N个404错误以及无效的404报警
- any feature?
> 完善isSlowNetwork方法的判断逻辑

- src/loader.ts
> 在 Android 5 和 6 上面，捕获了部分错误
> Unhandled promise rejection TypeError: r.attachShadow is not a function
> :bug: browser maybe only has createShadowRoot

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- any feature?
如果整个应用以 iframe 的形式被嵌入，那么应该允许 window.parent 和 window.top 逃逸出沙箱
> :bug: allow window.top & window.parent to escape sandbox while in iframe

- package.json
- src/sandbox/patchers/dynamicAppend.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/899)
> ✨ simulate document currentScript while dynamic loading

- examples/react16/src/components/HelloModal.js
- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- src/utils.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/897)
> 🐛 identify host app dynamic creation

- examples/react16/.rescriptsrc.js
close https://github.com/umijs/qiankun/issues/912
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/913)
> 🐛 fix dynamic append script with excludeAssetsFilter issue

- src/sandbox/patchers/dynamicAppend.ts
当我们在接入qiankun的时候，
发现其中的一个子项目有报错，
跟踪堆栈发现，是因为那个子项目中对于script标签都进行了onload事件监听，
并且使用了事件对象的target属性来获取src。
下面是伪代码：
```js
srcipt.onload = function(e) {
console.log(e.target.src)
}
```
由于qiankun派发的自定义事件中没有定义target，
所以报错了，
这个PR中的getPatchedCustomEvent方法为以后可能需要添加更多属性提供了准备。
> :bug: Allows the use of tag elements during script tag trigger events

- src/loader.ts
`const styleNodes = element.querySelectorAll('style')` 返回的是NodeList，在chrome51才开始支持，兼容之。
> 🐛  fix NodeList forEach method compatibility problem

- docs/api/README.md
- docs/api/README.zh.md
- docs/faq/README.md
- docs/faq/README.zh.md
> doc: add some frequently questions to the FAQ

- .eslintrc.js
- examples/main/multiple.js
- src/__tests__/utils.test.ts
- src/apis.ts
- src/utils.ts
ref https://github.com/umijs/qiankun/issues/518
简版缓存，通过 container 的 xpath + appName 的方式来判断后续的渲染是否要沿用之前已经计算过的 lifecycles，从而减少不必要的二次 load 的开销
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/986)
> ⚡️ cache for loadMicroApp

- src/apis.ts
- src/loader.ts
- src/utils.ts
ref https://github.com/umijs/qiankun/issues/518
支持 remount 时挂载到一个新的 container 节点上
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/992)
> ✨ support to pass a new container for remounting

- src/sandbox/patchers/css.ts
- src/sandbox/patchers/dynamicAppend/common.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1005)
> ✨ experimentalStyleIsolation support dynamic link style appending

- src/sandbox/patchers/css.ts
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1045)
> 🐛 fix the document.body returns undefined if we load qiankun in head script

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- 优化了沙箱劫持document.createElement的逻辑： 当qiankun运行在另一个沙箱下的时候，可能document已经被重写为新的实例，这个时候在`documentAttachProxyMap`内存储的是被重写document实例，而在`patchDocumentCreateElement`获取的时候，this指向的是原生的document，会导致无法获取`attachProxy`
> fix: 修复qiankun本身在沙箱下运行时，可能出现无法劫持document.createElement元素问题

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/proxySandbox.ts
子应用如果通过 eval 执行动态加载其他静态资源的代码，会泄露到主应用中
- any feature?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1052)
> ✨ hijack dynamic document appending in evalling code

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
当子应用重新给一个 non-enumerable 的属性赋值时，会导致沙箱将其以 enumerable 的形式加进去
- resolve https://github.com/umijs/qiankun/issues/777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1055)
> 🐛 keep the iteration order after reassign a non-enumerable value

- examples/main/webpack.config.js
- Automatically open browser after main app is built
- close https://github.com/umijs/qiankun/issues/1082
> feat: automatically open project demo in browser when running examples

- src/sandbox/common.ts
close https://github.com/umijs/qiankun/issues/1123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1133)
> 🐛 use Function.prototype.bind instead to avoid conflict while value has own bind function

- examples/vue3/src/components/HelloWorld.vue
Module Error (from ./node_modules/vue-loader-v16/dist/index.js):
<style vars> has been replaced by a new proposal: https://github.com/vuejs/rfcs/pull/231
- [√] `npm test` passes
- [√] tests are included
- [√] documentation is changed or added
- [√] commit message follows commit guidelines
本次PR 为 https://github.com/umijs/qiankun/pull/1135 的沟通后重新PR, 合并本次后, 可关闭1135
> 修复切换vue3时编译失败的问题;

- src/apis.ts
如果先使用 `start` 函数，默认的 `singular` 值会变成 `true`，再使用 `loadMicroApp` ， `singular`  就还是 `true`
> 🐛 Make sure singular is always false when using loadMicroApp

- .github/workflows/issue-reply.yml
> ci: add issue reply

- package.json
- src/apis.ts
- manual invoke single-spa start function for parcels
- resolve https://github.com/umijs/qiankun/pull/1071
- unlock single-spa
- resolve https://github.com/umijs/qiankun/pull/1314
- set urlRerouteOnly to true as default
- resolve https://github.com/umijs/qiankun/issues/1339
- resolve https://github.com/umijs/qiankun/issues/1184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/umijs/qiankun/1414)
> 🐛 manual invoke single-spa start function for parcels and set urlRerouteOnly true as default

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
> 🐛 add getPrototypeOf trap in sandbox to keep the `window instanceof Window` returns true in microapp

- package.json
> 🐛 fix scripts in package.json

- src/sandbox/patchers/dynamicAppend/common.ts
resolve https://github.com/umijs/qiankun/issues/1460
> 🐛 should not change currentScript if it not configurable

- src/loader.ts
- src/sandbox/patchers/interval.ts
- src/sandbox/snapshotSandbox.ts
- close https://github.com/umijs/qiankun/issues/1489
> fix clearInterval bug and ShadowDOM  bug for ie 10 and 11

- src/error.ts
- src/loader.ts
- add lifeCycles `beforeImport` and `afterImport`, which indicate the start and end of `importEntry stage`
> fix: error message

- src/sandbox/legacy/__tests__/sandbox.test.ts
- src/sandbox/legacy/sandbox.ts
umi mfsu 全量引了 cors-js，而 core-js 中通过 defineProperty 的方式[写了全局变量](https://github.com/zloirock/core-js/blob/c9c4397354f3e43727220ff8b08a3bf6c8c87cb5/packages/core-js/internals/set-global.js#L6)，导致 onex 场景会出错。
> ✨ loose sandbox support mutaion with defineProperty

- README.md
Proofread README.md, made some corrections and rewrites.
> 📝 a little polish and rewrite

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/common.ts
- src/sandbox/proxySandbox.ts
Keep the current sandbox getter as accurate as possible, might could resolve some issue about sandbox getting incorrect in multiple Instance scenario.
This change need to be test if it has a performance impact.
Probably it could fix https://github.com/umijs/qiankun/issues/1266
> 🎨 optimize current proxy setting logic

- src/index.ts
- src/sandbox/common.ts
- src/sandbox/index.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- src/sandbox/proxySandbox.ts
当 A 通过 qiankun 加载 B，B 又通过 qiankun 加载 C 时，可能出现 C 的 js 运行时，先走到了 B 沙箱的 getter trap，然后继续再触发 A 沙箱的 getter trap，从而导致即便在 B 应用中调用 getCurrentRunningApp 方法，拿到的确实 A 的实例，因为 getCurrentRunningApp 里面是通过全局变量去记录的
> ✨ remove global way for recording current running sandbox to fix nested scenario

- src/apis.ts
- src/utils.ts
- src/version.ts
从调用 loadMicroApp 触发加载开始，到应用开始触发 mount，由于期间是全异步流程，容器的 xpath 很容易就发生变化，从而出现最开始取到的跟后面的 xpath 不一致。比如在取容器的 lifecycle cache 时算出来的 xpath，跟取容器上一共关联过哪些微应用是算出来的 xpath 不一致，导致针对同一容器上多个微应用需要排队加载的行为失效
> 🐛 compute container xpath at beginning to keep it consist around app running

- src/sandbox/__tests__/common.test.ts
- src/sandbox/common.ts
有些工具函数，比如：
```js
function isNative() {  return typeof Ctor === 'function' && /native code/.test(Ctor.toString()) }
```
依赖于函数对象的`toString`方法的正确的返回值。目前 qiankun 沙箱中导出的函数，`toString`方法的返回值都是`function() {[native code]}`，导致上面的工具函数失灵。
我在社区里找到一个相关场景：
https://github.com/baidu/san/issues/627#issuecomment-876098885
[关闭这个 issue 的 commit](https://github.com/baidu/san/commit/800b35122e4f73232a603766c5a32cae08648f68)，就是使用了上文所述的`isNative`函数作 workaround。但就 qiankun 的实现而言，这个 workaround 应该没有解决问题。我在公司的项目里也遇到了类似的问题。
PR 的副作用是函数对象凭空多了一个实例方法`toString`。但是它的枚举性和之前一样，影响应该不算太大。在 Github 上搜整个社区的代码库，使用 `/native code/`做判断的代码，远比关心`hasOwnProperty('toString')`的代码要多。例如 [Vue 也用到了`isNative`](https://github.com/vuejs/vue/blob/0603ff695d2f41286239298210113cbe2b209e28/src/core/util/next-tick.js)
> fix: correct toString for functions

- src/sandbox/patchers/dynamicAppend/common.ts
由于 refChild 是可选参数，那么在 202 行和 215 行有可能将 undefined 作为 mountDOM.contains() 的参数。尽管通常情况下，将 undefined 作为参数时，浏览器并不会抛出错误，但是：
1. 根据 Web 标准，Node.contains() 的参数不是可选的，但是可以设置为 null（https://developer.mozilla.org/en-US/docs/Web/API/Node/contains）
2. 某些第三方的库，有可能会基于这个约定，来改写 contains 方法，这时就有可能出现错误
3. 事实上，百度地图的 webGL 版 js sdk 就改写了 contains 方法，尽管改写后的方法也没有兼容参数为 null 的情况 😒 ：
```js
// 百度地图 sdk 中的这段代码，没有考虑 contains 的参数为 null 或 undefined 的情况，造成我在主应用中加载 sdk 时报错了，我只能自己在项目中重新改写 `contains` 方法临时解决
if (typeof HTMLElement != "undefined" && !window.opera) {
HTMLElement.prototype.contains = function(e) {
if (e == this) {
return true
}
// 由于 qiankun 中调用这个方法时，e 为 undefined，导致浏览器抛出了错误
while (e = e.parentNode) {
if (e == this) {
return true
}
}
return false
}
}
```
以下为报错信息：
- any feature?
- close …
> fix: could pass `undefined` to Node.contains()

- src/sandbox/patchers/css.ts
Below ChromeV56，CSSMediaRule and CSSSupportsRule does't have conditionText prop.
Refer: https://developer.mozilla.org/zh-CN/docs/Web/API/CSSConditionRule
- any feature?
> fix: lower version chrome does't support css rule: conditionText #2128

- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forLooseSandbox.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
当出现如下操作路径时，原逻辑会出现 bug：
微应用 A 加载 -> remount（unmount -> mount），此时计数会为 { b:0, m: 1 }
微应用 B 加载 -> 同时触发 微应用 A 卸载，如果微应用 B 的 bootstrap 先触发了，计数会变为 { b:1, m:1 }，之后微应用 A 的 unmount 才开始执行，会判定 allAppsUnmounted 为 true，从而导致针对 document 的全局复写被回滚
> 🐛 fix the counter issue while multiple apps mounting concurrently

- package.json
- tsconfig.json
功能职责重复的 tslib 和 @babel/runtime 并存
去掉tslib只留@babel/runtime，能使构建出的包体检减少tslib的部分
> fix redundancy tslib & @babel/runtime to reduce build size

- src/__tests__/utils.test.ts
> :white_check_mark: add getContainerXPath test

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
- any feature?
- fix https://github.com/umijs/qiankun/issues/2300
> 🐛 should keep the property writable while it only have setter accessor

- src/sandbox/__tests__/proxySandbox.test.ts
- src/sandbox/proxySandbox.ts
~#2300~ (*#1804 [edited]*) has come up again, I think it's a bug in the code. Please review my code changes, just a little code change to swap the order of the two nested loops. And I also add an unit test to cover this case.
- any feature? No
- *[edited]* ~close #2300 again~ close #1804  again
> 🐛 proxy sandbox should not delete untouched globals

- src/loader.ts
Thus we could make sure that all assets are fetched while beforeLoad lifecycle calling, and the execScripts overhead is just js execution timing.
> 🐛 should trigger scripts loading before them executing

- package.json
- src/loader.ts
- src/sandbox/common.ts
- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/proxySandbox.ts
* resolves #2385 
* resolves #2386
> 🐛window variable should in with lexical scope while speedy mode enabled

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
考虑这个场景：
1. 主应用 A 嵌入 应用 B，沙箱配置为 speedy
2. 应用 B 嵌入应用 C，沙箱配置为非 speedy
3. C 启动时，因为沙箱未非 speedy，走原型链修改方式 patch document，此时会先获取原始的 createElement 方法，即 document.createElement -> proxyDocument.createElement
4. 将 proxyDocument.createElement 缓存作为原始 createElement 之后，B 实例化的沙箱会修改 Document.prototype.createElement
5. C 应用真实调用 document.createElement 时，实际调用链路为： Document.prototype.createElement 方法 -> 使用缓存的 proxyDocument.createElement -> proxyDocument.createElement 调用 document.createElement 创建元素 -> 使用 Document.prototype.createElement
6. 出现循环依赖，爆栈
> 🐛 compatible with nested sandbox to avoid stack overflow while createElement calling

- src/interfaces.ts
- src/utils.ts
Since working with Angular, setTimeout will be monkey patching by Zone.js, so when invoking nextTick
```javascript
const nextTick: (cb: () => void) => void =
typeof window.Zone === 'function' ? window.setTimeout : (cb) => Promise.resolve().then(cb);
``` 
Zone.js will hijack the callback. When the microTask queue is Empty, Zone.js will notify Angular to perform change detection.
This is correct, though. But during the change detection, Angular will still access the global variables, and qiankun will call nextTick to remove currentRunningApp mark:
```typescript
private registerRunningApp(name: string, proxy: Window) {
if (this.sandboxRunning) {
const currentRunningApp = getCurrentRunningApp();
if (!currentRunningApp || currentRunningApp.name !== name) {
setCurrentRunningApp({ name, window: …
```
> fix: invoking nextTick will trigger infinite angular change detection

- src/sandbox/patchers/dynamicAppend/__tests__/forStrictSandbox.test.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
When used as an argument, `document` should carry its own `Node` interface. If not invocations like
```javascript
const d = new Proxy(document, { /* handler */ }
d.createTreeWalker(d)
```
will throw
- any feature?
> fix: document proxy in strict sandbox mode replaces receiver with target in methods args

- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forLooseSandbox.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
嵌套沙箱场景，`document.createElement` 创建出来的元素会被每一层沙箱处理，且在后续 appendChild 时，也会因为 `isInvokedByMicroApp` 判断为 true 导致层层冒泡到最上层的沙箱，最终导致 element 被插到了最上层的微应用中，最后引入 bug，比如内层的微应用卸载时，自己动态插入的样式却没有卸载。
> 🐛 prevent element from processing multi times in nest sandbox

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
因为个别版本 Safari 中 typeof document.all === 'undefined'  和 typeof document.all === 'function' 都为 true，并且qiankun 中判断函数是否绑定过的方法 `isBoundedFunction` 里用到了 `fn.name.indexOf`，导致用到了 `document.all` 的地方会报错
- any feature?
> fix: document.all proxy error in naughtySafari

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
子应用里通过 `document.querySelector('head')` 获取到 target 后调用 target.appendChild 时，会因为不走代理后的 appendChild 方法导致样式劫持失效
> 🐛 document head in micro app should use the proxied appendChild methods

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
- resolve https://github.com/umijs/qiankun/issues/2495
> 🐛 support Node.prototype.compareDocumentPosition in sandbox

- src/sandbox/patchers/dynamicAppend/common.ts
- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
antd5 的 cssinjs 方案是通过 insertBefore 方式插入样式的，这时候会根据 referenceNode 为基准来决定插入位置，而不是无脑插入到 head 或 body 底部，此时需要提前记录地待 referenceNode 的位置信息，以便 remount 时根据位置还原现场
> 🐛 keep dynamic stylesheet inserted order by insertBefore way

- src/sandbox/common.ts
- resolve https://github.com/umijs/qiankun/issues/1209
> 🐛compatible with vConsole who will wrap global variables with proxy

- README.md
The `-S` flag is redundant above npm 4
> doc: remove the "-S" flag

- .changeset/tough-phones-chew.md
- packages/loader/src/index.ts
- packages/qiankun/src/core/loadApp.ts
- packages/sandbox/src/core/sandbox/StandardSandbox.ts
- packages/shared/src/assets-transpilers/index.ts
- packages/shared/src/assets-transpilers/script.ts
- packages/shared/src/assets-transpilers/utils.ts
- packages/shared/src/utils.ts
- ref https://github.com/umijs/qiankun/issues/2727
> 🐛 compatible with webpack chunk cache logic

- packages/loader/src/index.ts
- packages/qiankun/src/core/loadApp.ts
- packages/sandbox/src/core/compartment/globalProps.ts
- packages/sandbox/src/core/compartment/index.ts
- packages/sandbox/src/core/sandbox/globals.ts
- packages/sandbox/src/core/sandbox/index.ts
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- packages/sandbox/src/patchers/index.ts
- packages/sandbox/src/utils.ts
- packages/shared/src/assets-transpilers/types.ts
due to this newly eslint rule https://github.com/umijs/qiankun/blob/76b6bff7444c6f31afa6d4af498797f79b1e0d53/.eslintrc.cjs#L12
> fix: fix eslint error

- docs/faq/README.md
- docs/faq/README.zh.md
> fix: add faq

- .changeset/ninety-rivers-check.md
- packages/loader/src/index.ts
- packages/qiankun/src/core/loadApp.ts
- packages/qiankun/src/types.ts
1. Add transformer configuration for users who want to modify the entry HTML with a stream.
2. Remove the implementation of firstScriptStartLoadDeferred because the script execution in the entry is synchronous, and it doesn't make sense to insert asynchronous logic in the middle with beforeLoad. It cannot guarantee that beforeLoad will execute the sub-application script first and then execute. This will cause a breaking change for anyone using beforeLoad to monitor the performance of asset downloads.
> feat: add transformer options for app loader

- .husky/pre-commit
已经有了 lint-staged, 但是并没有在pre-commit时执行，很容易忘记执行，
所以添加了pre-commit
- any feature?
> chore: add pre-commit

- .changeset/twelve-donkeys-help.md
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- packages/sandbox/src/patchers/dynamicAppend/types.ts
直接修改 container 里的 qiankun head 元素，为其增加 appendChild 等方法，这样即便用户是通过 parentNode 这类方式一层层获取到 head 元素的，也可以确保后续的 appendChild 等操作一定会被代理
> fix: should patch the container head/body element immediately rather than patch its functions with proxy

- .changeset/thin-ways-allow.md
- packages/loader/src/index.ts
- Use the onload/onerror approach to listen to script events in order to follow the writable-dom.
- Our script load listener should be invoked before the script's own listener, as the listener might append another script, thus causing our entry to be fired delayed.
> fix(loader): we should invoke our script load listener before its own

- CONTRIBUTING-zh.md
- CONTRIBUTING.md
- README.md
> docs: add contributing guide

- .changeset/four-worms-think.md
- .eslintrc.cjs
- .husky/pre-commit
- .prettierignore
- package.json
- packages/loader/package.json
- packages/loader/src/index.ts
- packages/qiankun/package.json
- packages/sandbox/package.json
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- packages/sandbox/src/patchers/dynamicAppend/types.ts
- packages/shared/package.json
- packages/shared/src/assets-transpilers/index.ts
- packages/shared/src/assets-transpilers/script.ts
- packages/shared/src/assets-transpilers/types.ts
- packages/shared/src/utils.ts
- packages/ui-bindings/react/package.json
- packages/webpack-plugin/package.json
- pnpm-lock.yaml
- tsconfig.json
Non-async scripts loaded asynchronously need to ensure execution order consistent with browser behavior.
> feat(sandbox): support dynamic sync scripts executed by order in sandbox

- src/sandbox/patchers/dynamicAppend/forStrictSandbox.ts
当子应用复写了 document.createElement 的时候，会导致全局的 document.createElement 也被改写，从而导致主应用的元素创建也被视为子应用，比如子应用中这样一段代码：
```js
const nativeCreateElement = document.createElement;
document.createElement = (...args) => {
return nativeCreateElement.call(document, ...args);
}
```
> fix: createElement hijack must be paired to avoid rewriting leak

- src/sandbox/common.ts
- src/sandbox/proxySandbox.ts
在一个 800 个元素左右的数组迭代里，每次都调用 object spread，会花掉接近 80ms 的 cpu 时间
- any feature?
> ⚡️ remove object spread operator for faster performance in big array iterator

- .changeset/smart-scissors-sell.md
- packages/loader/src/index.ts
- packages/qiankun/src/core/loadApp.ts
- packages/qiankun/src/utils.ts
- packages/sandbox/src/patchers/dynamicAppend/common.ts
- packages/sandbox/src/patchers/dynamicAppend/forStandardSandbox.ts
- packages/shared/src/assets-transpilers/types.ts
> fix: dynamic append element should support for the same container between micro apps

- .changeset/empty-lions-rescue.md
- packages/shared/src/assets-transpilers/__tests__/script.test.ts
- packages/shared/src/assets-transpilers/script.ts
- resolves https://github.com/umijs/qiankun/issues/2694
> fix: remove inline script source-url

- .changeset/forty-teachers-taste.md
- examples/main/package.json
- examples/main/render/ReactRender.jsx
- examples/main/webpack.config.js
- examples/react15/package.json
- examples/react16/.rescriptsrc.js
- packages/ui-bindings/react/package.json
- packages/ui-bindings/react/src/MicroApp.tsx
- packages/ui-bindings/shared/src/index.ts
- packages/ui-bindings/vue/package.json
- packages/ui-bindings/vue/src/MicroApp.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
1. 补充 react microapp 的 demo
2. name & entry 必填
3. 前一个子应用出错后，可以加载其他子应用
4. 复用 microapp，name 属性变化时，等待前一个子应用卸载完成
> feat: refactor-microapp

- src/sandbox/__tests__/snapshotSandBox.test.ts
- src/sandbox/snapshotSandbox.ts
Ensure that delete props in the snapshotSandbox not affect the global environment
- resolve https://github.com/umijs/qiankun/issues/2629
> fix:  snapshotSandbox delete props escape to window

- .changeset/orange-boats-allow.md
- packages/qiankun/src/core/loadApp.ts
- packages/shared/src/assets-transpilers/script.ts
当且仅当文档上同时挂载`同一个应用多次`时，需要移除 webpack 的缓存，从而避免后续挂载的子应用实例因为命中了 webpack 的缓存，从而不再新建对应的 chunk script，导致 chunk 缺失
- ref https://github.com/umijs/qiankun/issues/2727
> feat: remove webpack chunk cache attributes just while there are multi instances loaded on document

- .changeset/rich-parents-relate.md
- examples/main/render/Vue3Render.js
- packages/qiankun/src/version.ts
- packages/ui-bindings/vue/README.md
- packages/ui-bindings/vue/README.zh-CN.md
- packages/ui-bindings/vue/src/MicroApp.ts
1. 注册 umount hook 卸载子应用
2. 提供 appProps 作为属性传递给子应用，防止被注册为 attributes
related issue: https://github.com/umijs/qiankun/issues/2846
> fix(vue): add unmount hook to unmount application

- src/sandbox/patchers/windowListener.ts
场景1:当用户通过addEventlistener多次添加同一个监听时，如果listener和capture/useCapture都相同，浏览器会认为是同一个监听，后添加的监听会覆盖之前添加的监听，取消的时候也只需要取消一次；
场景2:另外当options的once为true时，如果监听执行了是不需要取消的。
问题：针对以上两种情形，如果用户多次添加同一个监听，或者options中的once设为true，没有移除监听，就会导致listenerMap中的监听无法移除。
解决方案：针对多次添加同一个监听情况做判断，如果是同一个监听capture/useCapture都相同，则先移除之前的监听在添加新的监听，针对once场景，当监听执行后自动移除listenerMap中的监听。
> fix:addEventlistener memory leak.

- .changeset/small-experts-hug.md
- packages/sandbox/src/patchers/windowListener.ts
#2883 同步master分支中支持addEventListener和once选项，以避免内存泄漏
> [fix] supports the addEventListener and once options to avoid memory leaks

- .changeset/poor-squids-hide.md
- packages/qiankun/src/apis/loadMicroApp.ts
* resolves #1885
* resolves #2166
* resolves #1990
* resolves #2854
> fix(qiankun): should remove internal cache of loadMicroApp while loading failed

- .changeset/red-islands-mate.md
- packages/loader/src/index.ts
- packages/loader/src/utils.ts
- packages/qiankun/src/core/loadApp.ts
entry 可能是相对路径，如 `/index.html`，直接在 loadEntry 入参里区分是外链还是已经有内容的，而不是通过字符串判断
> feat(loader): supports passing Response as entry parameter for loadEntry function

- .changeset/smart-guests-jam.md
- packages/sandbox/src/patchers/windowListener.ts
* ref https://github.com/umijs/qiankun/pull/2883
> chore: optimize code
